### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by detartsurf** [alexzuza/angular-plugin-architecture-with-module-federation#2]
On a clean development system. Not enough information is given to build this sample. What are the prerequisites?
I get the following error when running npm run start.

------------------------------------------------------------------------------
Built Angular Package
 - from: C:\Samples\angular-plugin-architecture-with-module-federation\projects\shared
 - to:   C:\Samples\angular-plugin-architecture-with-module-federation\dist\shared
------------------------------------------------------------------------------

> angular-plugin-architecture-module-federation@0.0.0 build:plugins C:\Samples\angular-plugin-architecture-with-module-federation
> ng build plugins --prod

Warning: License extraction is currently disabled when using Webpack 5. This is temporary and will be corrected in a future update.
Compiling shared : es2015 as esm2015
87% sealing module hashingC:\Samples\angular-plugin-architecture-with-module-federation\node_modules\webpack\lib\Module.js:707
                hash.update(chunkGraph.getModuleGraphHash(this, runtime));
                                       ^

TypeError: chunkGraph.getModuleGraphHash is not a function
    at ContainerEntryModule.updateHash (C:\Samples\angular-plugin-architecture-with-module-federation\node_modules\←[4mwebpack←[24m\lib\Module.js:707:26)
    at Compilation.createModuleHashes (C:\Samples\angular-plugin-architecture-with-module-federation\node_modules\←[4m@angular-devkit←[24m\build-angular\node_modules\←[4mwebpack←[24m\lib\Compilation.js:2618:12)
    at C:\Samples\angular-plugin-architecture-with-module-federation\node_modules\←[4m@angular-devkit←[24m\build-angular\node_modules\←[4mwebpack←[24m\lib\Compilation.js:1956:11
    at eval (eval at create (C:\Samples\angular-plugin-architecture-with-module-federation\node_modules\←[4mtapable←[24m\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at C:\Samples\angular-plugin-architecture-with-module-federation\node_modules\←[4m@angular-devkit←[24m\build-angular\node_modules\←[4mwebpack←[24m\lib\optimize\ModuleConcatenationPlugin.js:449:32
←[90m    at processTicksAndRejections (internal/process/task_queues.js:79:11)←[39m

**Comment by TECHNOFAB11** [comment]
+1, would be great to have a written guide or even a video explaining how it works and how to run it/implement it in other projects

**Comment by Slicit** [comment]
Made for the 🐻  ! no time for documentation 🤢  !
